In [10]:
%cd /tf/notebooks/notebooks
%pip install pandas
%pip install scikit-learn
%pip install openpyxl

[Errno 2] No such file or directory: '/tf/notebooks/notebooks'
/tf

/usr/local/lib/python3.11/dist-packages/IPython/core/magics/osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.5.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.
Collecting openpyxl
  Downloading openpyxl-3.1.3-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.3-py2.py3-none-any.whl (251 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.3/251.3 kB 5.3 MB/s eta 0:00:00a 0:00:01
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd

data_path = '/tf/notebooks/olympic_final.xlsx'
df = pd.read_excel(data_path)

In [12]:
df.head()

,discipline_title,event_title,event_gender,participant_type,athlete_full_name,country_name,games_participations,athlete_year_birth,nb_gold,nb_silver,nb_bronze,Medals,game_end_date,game_start_date,game_location,game_season,game_year,city_location
0,Curling,Mixed Doubles,Mixed,GameTeam,Stefania CONSTANTINI,Italy,1,1999,1,0,0,1,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Winter,2022,Beijing
1,Curling,Mixed Doubles,Mixed,GameTeam,Amos MOSANER,Italy,2,1995,1,0,0,1,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,Winter,2018,PyeongChang
2,Curling,Mixed Doubles,Mixed,GameTeam,Kristin SKASLIEN,Norway,2,1986,0,1,1,2,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,Winter,2018,PyeongChang
3,Curling,Mixed Doubles,Mixed,GameTeam,Magnus NEDREGOTTEN,Norway,2,1990,0,1,1,2,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,Winter,2018,PyeongChang
4,Curling,Mixed Doubles,Mixed,GameTeam,Almida DE VAL,Sweden,1,1997,0,0,1,1,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Winter,2022,Beijing

In [16]:
# drop all winter
df = df[df['game_season'] == 'Summer']

# drop 'game_season' column
df = df.drop(columns=['game_season'])

In [17]:
df.head()

,discipline_title,event_title,event_gender,participant_type,athlete_full_name,country_name,games_participations,athlete_year_birth,nb_gold,nb_silver,nb_bronze,Medals,game_end_date,game_start_date,game_location,game_year,city_location
176,Alpine Skiing,Men's Alpine Combined,Men,Athlete,James CRAWFORD,Canada,2,1997,0,0,1,1,1936-08-16T19:00:00Z,1936-08-01T07:00:00Z,Germany,1936,Berlin
212,Cross Country Skiing,Men's Team Sprint Classic,Men,GameTeam,Alexander BOLSHUNOV,Russia,2,1996,3,1,1,5,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,2016,Rio
214,Cross Country Skiing,Men's 15km + 15km Skiathlon,Men,Athlete,Alexander BOLSHUNOV,Russia,2,1996,3,1,1,5,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,2016,Rio
226,Cross Country Skiing,Men's 50km Mass Start Free,Men,Athlete,Alexander BOLSHUNOV,Russia,2,1996,3,1,1,5,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,2016,Rio
231,Cross Country Skiing,Men's 15km Classic,Men,Athlete,Alexander BOLSHUNOV,Russia,2,1996,3,1,1,5,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,2016,Rio

In [ ]:
df = df.drop(columns=['game_end_date', 'game_start_date'])

In [18]:
df_for_gold = df.copy().drop(columns=['nb_silver', 'nb_bronze', 'Medals'])
df_for_silver = df.copy().drop(columns=['nb_gold', 'nb_bronze', 'Medals'])
df_for_bronze = df.copy().drop(columns=['nb_gold', 'nb_silver', 'Medals'])
df_for_total = df.copy().drop(columns=['nb_gold', 'nb_silver', 'nb_bronze'])